test_moni/apps/loans/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='apply_loan')),

    path('loans/apply/', include([
        path('', views.LoanFormView.as_view(), name='apply_loan'),
        path('validate/', views.LoanValidatorCreateAPIView.as_view(), name='validate_loan'),
    ])),

    # Admin site urls
    path('admin/', include([
        path('', RedirectView.as_view(pattern_name='list_loans')),

        path('loans/', login_required(views.LoanListView.as_view()), name='list_loans'),

        path('loans/<int:pk>/', include([
            path('', login_required(views.LoanDetailView.as_view()), name='detail_loan'),
            path('edit/', login_required(views.LoanUpdateView.as_view()), name='update_loan'),
            path('delete/', login_required(views.LoanDeleteView.as_view()), name='delete_loan'),
        ])),
    ])),
]

test_moni/test_moni/urls.py
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', include('apps.loans.urls')),
]

test_moni/apps/loans/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy


class Loan(models.Model):
    """
    Represents a loan.
    """
    APPROVED_CHOICES = (
        (True, 'Approved'),
        (False, 'Not approved'),
    )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    is_active = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=False, choices=APPROVED_CHOICES)

    document_number = models.PositiveIntegerField()
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField(max_length=128)
    amount = models.DecimalField(decimal_places=2, max_digits=16)

    def delete(self):
        self.is_active = False
        self.save()

    def get_absolute_url(self):
        return reverse_lazy('list_loans')


class LoanAdmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

test_moni/apps/loans/forms.py
from django import forms

from .models import Loan


class LoanModelForm(forms.ModelForm):

    class Meta:
        model = Loan
        fields = (
            'document_number',
            'first_name',
            'last_name',
            'gender',
            'email',
            'amount',
        )

test_moni/apps/loans/views.py
import requests

from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, FormView, UpdateView
from django.views.generic.list import ListView

from rest_framework.generics import CreateAPIView

from .forms import LoanModelForm
from .mixins import LoanAdminLoginMixin
from .models import Loan
from .serializers import LoanModelSerializer


class LoanValidatorCreateAPIView(CreateAPIView):
    """
    Validates a loan by an external api.
    """
    BASE_URL_API = 'http://scoringservice.moni.com.ar:7001/api/v1/scoring/'

    queryset = Loan.objects.all()
    serializer_class = LoanModelSerializer

    def perform_create(self, serializer):
        # Get the parameters needed to make the api call
        params = {
            'document_number': serializer.validated_data['document_number'],
            'gender': serializer.validated_data['gender'],
            'email': serializer.validated_data['email']
        }

        # Check the loan data, and set is_approved according to the response
        response = requests.get(self.BASE_URL_API, params)
        loan_is_approved = response.json().get('approved', False)

        serializer.save(is_approved=loan_is_approved)


class LoanFormView(FormView):
    """
    Renders the loan application form.
    """
    form_class = LoanModelForm
    template_name = 'loans/apply.html'


class LoanListView(LoanAdminLoginMixin, ListView):
    template_name = 'loans/list.html'
    queryset = Loan.objects.filter(is_active=True)


class LoanDetailView(LoanAdminLoginMixin, DetailView):
    model = Loan
    template_name = 'loans/detail.html'


class LoanUpdateView(LoanAdminLoginMixin, UpdateView):
    model = Loan
    form_class = LoanModelForm
    template_name = 'loans/edit.html'


class LoanDeleteView(LoanAdminLoginMixin, DeleteView):
    model = Loan

    def get_success_url(self):
        return reverse('list_loans')

test_moni/templates/loans/_base.html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    {% block js %}{% endblock %}
</html>

test_moni/templates/loans/_form.html
<form method="post" id="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

<p id="msg"></p>

test_moni/templates/loans/apply.html
{% extends './_base.html' %}

{% load static %}

{% block content %}
  {% include './_form.html' %}
{% endblock content %}

{% block js %}
  <script type="text/javascript" src="{% static 'js/loans/apply.js' %}"></script>
{% endblock js %}

test_moni/templates/loans/detail.html
{% extends './_base.html' %}

{% block content %}
  <p># {{ loan.id }}</p>
  <p>Document Number: {{ loan.document_number }}</p>
  <p>First Name: {{ loan.first_name }}</p>
  <p>Last name: {{ loan.last_name }}</p>
  <p>Gender: {{ loan.gender }}</p>
  <p>Email: {{ loan.email }}</p>
  <p>Amount $ {{ loan.amount }}</p>
  <p>Status: {{ loan.get_is_approved_display }}</p>
  <hr />
  <a href="{% url 'list_loans' %}">Back</a> <a href="{% url 'account_logout' %}">Logout</a>
{% endblock content %}

test_moni/templates/loans/edit.html
{% extends './_base.html' %}

{% load static %}

{% block content %}
  {% include './_form.html' %}
{% endblock content %}

test_moni/templates/loans/list.html
{% extends './_base.html' %}

{% block content %}

  {% for loan in loan_list %}
    <h3>#{{ loan.id }} - $ {{ loan.amount }} {{ loan.last_name }}, {{ loan.first_name }}</h3>
    <a href="{% url 'detail_loan' loan.pk %}">View</a>
    <a href="{% url 'update_loan' loan.pk %}">Edit</a>
    <a href="{% url 'delete_loan' loan.pk %}">Delete</a>
  {% empty %}
    <p>There is no loans to show.</p>
  {% endfor %}

<hr />
<a href="{% url 'account_logout' %}">Logout</a>

{% endblock content %}

test_moni/templates/loans/loan_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  The following object will be deleted. Are you sure?

  <p># {{ loan.id }}</p>
  <p>Document Number: {{ loan.document_number }}</p>
  <p>First Name: {{ loan.first_name }}</p>
  <p>Last name: {{ loan.last_name }}</p>
  <p>Gender: {{ loan.gender }}</p>
  <p>Email: {{ loan.email }}</p>
  <p>Amount $ {{ loan.amount }}</p>
  <p>Status: {{ loan.get_is_approved_display }}</p>

  <input type="submit" value="Confirm deletion" name="confirm_delete" />
</form>

<hr />
<a href="{% url 'list_loans' %}">Back</a> <a href="{% url 'account_logout' %}">Logout</a>